# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-26 06:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20170826_0630'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RestaurantLocation',
            new_name='Restaurant',
        ),
    ]
